use different build directories for debug/production

diff --git a/bs b/bs
--- a/bs
+++ b/bs
@@ -10,7 +10,11 @@ PROJECT_NAME="Piano960"
 
 PIANO960_REPO=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd );
 
-PIANO960_BUILD_DIRECTORY=$PIANO960_REPO/build
+ALL_BUILDS_DIRECTORY=$PIANO960_REPO/Builds
+
+DEBUG_BUILD_DIRECTORY=$ALL_BUILDS_DIRECTORY/debug-build
+
+PRODUCTION_BUILD_DIRECTORY=$ALL_BUILDS_DIRECTORY/production-build
 
 PIANO960_INSTALL_PREFIX=/usr/local
 
@@ -40,7 +44,41 @@ USE_LOG=false;
 
 CATCH2_ARGS="";
 
-echo_help_message() 
+MAKE_PARAMETERS="Piano960Plugin";
+
+###########################################################################################
+###########################################################################################
+
+print()
+{
+    if [ "$SILENT" = false ]; then
+        echo "    <> [BUILD:INFO] | $@";
+    fi
+}
+
+verbose_print() 
+{
+    if [ "$VERBOSE" = true ]; then 
+        print "$@";
+    fi
+}
+
+verbose_print_command()
+{
+    if [ "$VERBOSE" = true ]; then
+        echo "    <> [BUILD:STDIN] | $@";
+    fi
+}
+
+exit_with_error_message() 
+{ 
+    echo; 
+    echo "<<<ERROR>>> | $@"; 
+    echo; 
+    exit;
+}
+
+print_help_message() 
 {
     echo "options:";
     echo "v   Print out verbose information";
@@ -58,36 +96,8 @@ echo_help_message()
     echo "u   can be used to pass arguments into unit test build";
 }
 
-pushd_silently() { command pushd "$@" > /dev/null; }
-popd_silently()  { command popd "$@" > /dev/null; }
-
-echo_stdin_message() { echo; echo "[STDIN]: $@"; echo; }
-echo_build_message() { echo; echo "[BUILD MESSAGE]: $@"; echo; }
-exit_with_error()    { echo; echo "[ERROR]: $@"; echo; exit; }
-
-verbose_print() 
-{
-    if [ "$VERBOSE" = true ]; then 
-        echo_stdin_message "$@"; 
-    fi
-}
-
-create_piano960_build_directory()
-{
-    echo_build_message "creating Piano960 build directory: $PIANO960_BUILD_DIRECTORY";
-
-    if [ "$VERBOSE" = true ]; then echo_stdin_message "mkdir $PIANO960_BUILD_DIRECTORY"; fi
-    mkdir $PIANO960_BUILD_DIRECTORY;
-
-    if [ ! -d "$PIANO960_BUILD_DIRECTORY" ]; then
-        exit_with_error "something went wrong while creating the build directory...";
-    fi
-}
-
 cmake_piano960() 
 {
-    pushd_silently $PIANO960_BUILD_DIRECTORY;
-
     cmake_command_arguments="-DCMAKE_INSTALL_PREFIX=$PIANO960_INSTALL_PREFIX -DPITCH_DETECTION=${PITCH_DETECTION_ALGO}";
 
     if [ "$ENABLE_GPU" = true ]; then
@@ -98,71 +108,62 @@ cmake_piano960()
         cmake_command_arguments="${cmake_command_arguments} -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++";
     fi
 
-    if [ "$DEBUG_BUILD" = true ]; then
-        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_BUILD_TYPE=Debug";
-    else
+    if [ "$PRODUCTION" = true ]; then
         cmake_command_arguments="${cmake_command_arguments} -DCMAKE_BUILD_TYPE=Release";
+    else
+        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_BUILD_TYPE=Debug";
     fi
 
     if [ "$USE_LOG" = true ]; then
         cmake_command_arguments="${cmake_command_arguments} -DUSE_LOG=ON";
     fi
 
+    # ------------------------------
 
-    if [ "$VERBOSE" = true ]; then 
-        echo_stdin_message "cmake $PIANO960_REPO $cmake_command_arguments";
-        cmake $PIANO960_REPO $cmake_command_arguments;
-    elif [ "$SILENT" = true ]; then
+    if [ "$SILENT" = true ]; then
         cmake $PIANO960_REPO $cmake_command_arguments > /dev/null;
     else
+        verbose_print_command "cmake $PIANO960_REPO $cmake_command_arguments";
         cmake $PIANO960_REPO $cmake_command_arguments;
     fi
 
     if [ $? -ne 0 ]; then
-        exit_with_error "'cmake' command failed ('cmake $PIANO960_REPO'). Exiting.";
+        exit_with_error_message "'cmake' command failed ('cmake $PIANO960_REPO'). Exiting.";
     fi
-
-    popd_silently;
 }
 
 make_piano960()
 {
-    pushd_silently $PIANO960_BUILD_DIRECTORY;
-
     make_command_arguments="$@";
-    if [ "$VERBOSE" = true ]; then echo_stdin_message "make $make_command_arguments"; fi
 
     if [ "$SILENT" = true ]; then
         make $make_command_arguments > /dev/null;
     else
+        verbose_print_command "make $make_command_arguments";
         make $make_command_arguments;
     fi
 
     if [ $? -ne 0 ]; then
-        exit_with_error "'make' command failed. Exiting.";
+        exit_with_error_message "'make' command failed. Exiting.";
     fi
-
-    popd_silently;
 }
 
-# 1) --- handle user input ---
+###########################################################################################
+###########################################################################################
 
-# TODO: support full word options (e.g. --verbose)
+# 1) --- parse cli options ---
 
-make_parameters="Piano960Plugin" # this gets passed to the 'make' command
-function add_make_parameter() { make_parameters="${make_parameters} $@"; }
-
-while getopts "hvscit23degatfalu:" option; do
+while getopts "hvscit23pegatfalu:x" option; do
    case $option in
-      h) echo_help_message; exit;;                          # -h : display help message
-      v) VERBOSE=true;;                                     # -v : turn on verbose mode
-      s) SILENT=true;;                                      # -s : turn on silent mode
-      c) CLEAN_BUILD=true;;                                 # -c : make clean build
-      i) add_make_parameter "install";;                     # -i : install samples
-      t) add_make_parameter "unit-tests"; RUN_TESTS=true;;  # -t : build and run unit tests
-      2) PITCH_DETECTION_ALGO="SPICE";;                     # -2 : use spice model for pitch detection
-      3) PITCH_DETECTION_ALGO="CREPE";;                     # -3 : use crepe model for pitch detection
-      d) DEBUG_BUILD=false;;
+      h) print_help_message; exit;;
+      v) VERBOSE=true;;
+      s) SILENT=true;;
+      c) CLEAN_BUILD=true;;
+      i) MAKE_PARAMETERS="${MAKE_PARAMETERS} install";;
+      t) MAKE_PARAMETERS="${MAKE_PARAMETERS} unit-tests"; RUN_TESTS=true;;
+      2) PITCH_DETECTION_ALGO="SPICE";;
+      3) PITCH_DETECTION_ALGO="CREPE";;
+      p) PRODUCTION=true;;
       e) ENABLE_GPU=true;;
       g) USE_GCC=true;;
       a) ABORT_AFTER_FIRST_TEST_FAILURE=true;;
@@ -172,35 +173,57 @@ while getopts "hvscit23degatfalu:" option; do
    esac
 done
 
-# 2) --- create build files ---
+# 2) --- setup build directory ---
 
-if [ -d "$PIANO960_BUILD_DIRECTORY" ] && [ "$CLEAN_BUILD" = true ]; then
-    if [ "$VERBOSE" = true ]; then 
-        echo_stdin_message "rm -rf" $PIANO960_BUILD_DIRECTORY; 
-    fi
-
-    rm -rf $PIANO960_BUILD_DIRECTORY;
+if [ ! -d "$ALL_BUILDS_DIRECTORY" ]; then 
+    verbose_print_command "mkdir $ALL_BUILDS_DIRECTORY";
+    mkdir $ALL_BUILDS_DIRECTORY;
 fi
 
-if [ ! -d "$PIANO960_BUILD_DIRECTORY" ]; then 
-    create_piano960_build_directory;
-    cmake_piano960;
-elif [ "$CLEAN_BUILD" = true ]; then
-    cmake_piano960;
+if [ "$PRODUCTION" = true ]; then
+    BUILD_DIRECTORY=$PRODUCTION_BUILD_DIRECTORY;
+else
+    BUILD_DIRECTORY=$DEBUG_BUILD_DIRECTORY;
 fi
 
-# 3) --- build the executable(s) ---
+if [ "$CLEAN_BUILD" = true ]; then
+    verbose_print_command "rm -rf $BUILD_DIRECTORY";
+    rm -rf $BUILD_DIRECTORY;
+fi
 
+if [ ! -d "$BUILD_DIRECTORY" ]; then
+    verbose_print_command "mkdir $BUILD_DIRECTORY";
+    mkdir $BUILD_DIRECTORY;
+fi
+
+# 3) --- build the plugin ---
+
+working_directory=$(pwd);
+
+verbose_print_command "cd $BUILD_DIRECTORY";
+cd $BUILD_DIRECTORY;
+
+cmake_piano960;
 make_piano960 $make_parameters;
 
+verbose_print_command "cd $working_directory";
+# cd $working_directory;
+
+if [ $? -eq 0 ]; then
+    print "Successfully built Piano960 to $BUILD_DIRECTORY";
+else
+    print "Failed to build Piano960 to $BUILD_DIRECTORY";
+    exit;
+fi
+
+# 3) --- run the unit tests (if '-t' cli option was set) ---
+
 if [ "$RUN_TESTS" = true ]; then
-    # if -t option was set, run the newly built unit tests 
+
     testQuery=$CATCH2_ARGS;
 
-
     if [ "$ONLY_RUN_FAST_TESTS" = true ]; then
-        excludeSlowTestsQuery=~[slow];
-        testQuery="$CATCH2_ARGS$excludeSlowTestsQuery";
+        testQuery="$CATCH2_ARGS~[slow]";
     fi
 
     testArgs=$testQuery;
@@ -208,21 +231,11 @@ if [ "$RUN_TESTS" = true ]; then
     if [ "$ABORT_AFTER_FIRST_TEST_FAILURE" = true ]; then
         testArgs="$testArgs --abort";
     fi
-
-    # if [ "$VERBOSE" = true ]; then
-    #     testArgs="$testArgs -?";
-    # fi
-
     if [ "$LIST_TESTS" = true ]; then
         testArgs="$testArgs --list-tests";
     fi
 
-    unitTestExecutable=$PIANO960_BUILD_DIRECTORY/Tests/unit-tests;
-
-    verbose_print "$unitTestExecutable $testArgs";
-
-    $unitTestExecutable $testArgs
+    verbose_print_command "$BUILD_DIRECTORY/Tests/unit-tests $testArgs";
+    $BUILD_DIRECTORY/Tests/unit-tests $testArgs
 fi
-
-echo_build_message "Successfully built Piano960 to" $PIANO960_BUILD_DIRECTORY;
 
